version: "2.1"

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./.test
      dockerfile: Dockerfile
    command: sh /docker_test.sh
    depends_on:
      - pdns-server
      - pdns-mysql
    environment:
      # Tests setup
      - PING_CONTAINER=pdns-server
    volumes_from:
      - pdns-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  pdns-server:
    build: .
    image: ${IMAGE_NAME}
    hostname: ${PDNS_HOST}
    container_name: ${PDNS_HOST}
    ports:
      - "5053:53"
      - "5053:53/udp"
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MYSQL_AUTOCONF=true
      #- AUTOCONF=mysql
      # MySQL / MariaDB
      - MYSQL_HOST=${PDNS_DB_HOST}
      - MYSQL_PORT=3306
      - MYSQL_DB=${PDNS_DB_NAME}
      - MYSQL_USER=${PDNS_DB_USER}
      - MYSQL_PASS=${PDNS_DB_PASSWORD}
      - MYSQL_DNSSEC=no
      # PDNS Config
      - PDNS_API=yes
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_WEBSERVER_ADDRESS=0.0.0.0
      - PDNS_WEBSERVER_PORT=8081
      - PDNS_WEBSERVER_ALLOW_FROM=${PDNS_WEBSERVER_ALLOW_FROM}/0
      - PDNS_SOA_REFRESH_DEFAULT=14400
    depends_on:
      pdns-mysql:
        condition: service_healthy

  pdns-mysql:
    image: mariadb:10.3
    hostname: ${PDNS_DB_HOST}
    container_name: ${PDNS_DB_HOST}
    mem_limit: 256M
    memswap_limit: 256M
    expose:
      - 3306
    volumes:
      - powerdns-mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - default
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
    environment:
      - MYSQL_DATABASE=${PDNS_DB_NAME}
      - MYSQL_USER=${PDNS_DB_USER}
      - MYSQL_PASSWORD=${PDNS_DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

networks:
  default:

volumes:
  powerdns-mysql-data:
