version: "2.1"

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./.test
      dockerfile: Dockerfile
    command: sh /docker_test.sh
    depends_on:
      - pdns-server-sqlite
    environment:
      # Tests setup
      - PING_CONTAINER=pdns-server-sqlite
    volumes_from:
      - pdns-server-sqlite
    networks:
      - pdns-compose-sqlite
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  pdns-server-sqlite:
    build: .
    image: ${IMAGE_NAME}
    hostname: ${PDNS_HOST}
    container_name: pdns-server-sqlite
    ports:
      - "5053:53"
      - "5053:53/udp"
    networks:
      - pdns-compose-sqlite
    volumes:
      - powerdns-sqlite-data:/srv/pdns/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - AUTOCONF=sqlite
      # SQLite
      - SQLITE_DB=/srv/pdns/db/${PDNS_DB_NAME}
      - SQLITE_DNSSEC=no
      # PDNS Config
      - PDNS_LOG_DNS_QUERIES=yes
      - PDNS_API=yes
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_WEBSERVER=no
      - PDNS_WEBSERVER_ADDRESS=0.0.0.0
      - PDNS_WEBSERVER_PORT=8081
      - PDNS_WEBSERVER_ALLOW_FROM=${PDNS_WEBSERVER_ALLOW_FROM}/0
      - PDNS_SOA_REFRESH_DEFAULT=14400

networks:
  pdns-compose-sqlite:

volumes:
  powerdns-sqlite-data:
